name: Run Python File

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Run all Python files
        run: |
          echo "Running all .py files in repo..."
          for file in $(find . -name "*.py"); do
            echo "🐍 Running $file"
            python "$file"
          done
